### ISSUE TITLE
Finish Linkdrop v2 UI

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#1]
## 🎉   Subtasks

- [x]  Iterate if Volodymyr is missing any screens, and define missing user-stories based on this
- [x] Add QR code into UI
- [x] Add error screens
- [x] Hand-over to Volodymyr with CSS specified (via Zeppelin or Figma)

## 🤼‍♂️   Reviewer

@Kisgus @eclipseeer 

## 🔗   Work doc(s) / inspirational links

https://app.zeplin.io/project/60211b08d6a191177ace29cc/dashboard?tag=Start
