### ISSUE TITLE
Coordinate MVP of Linkdrop Analytics with NEAR Analytics Team and other stakeholders

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#10]
## 📋   Anything to add?

Make sure we develop the MVP of Linkdrop analytics in the easiest way possible

## 🎉   Subtasks

- [x] Provide an overview of our "minium on-chain analytics"
- [x] Identify all analytics stakeholders
- [x] Setup a call and understand easiest way to go about 
- [x] Create specification and setup issues for Linkdrop MVP analytics 

## 🤼‍♂️   Reviewer

@AngelBlock

**Comment by Kisgus** [comment]
Done, created #19 as a result
