### ISSUE TITLE
Soft Launch of Linkdrop v2

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#11]
## 📋   Anything to add?

Lets launch this baby

## 🎉   Subtasks

- [x] When #7 is done
- [x] Change URL to app.linkdrop.tech
- [x] Iterate with internal stakeholders and stress-test on mainnet
- [x] Start work on official launch

## 🤼‍♂️  Reviewer

@Kisgus @AngelBlock
