### ISSUE TITLE
Sputnik DAO v1 Stats

### ISSUE THREAD

**Issue by AngelBlock** [NEAR-labs/labs-kanban#12]
## 📋   SputnikDAO is a hub of DAOs empowering communities in the NEAR ecosystem with new tools for decision-making, coordination, and on-chain representation. 

SputnikDAO Stats is an app which collects the data from DAO contracts and transactions and displays them in user-friendly format.

## 🎉   Subtasks

- [ ] @Kisgus move site hosting to the foundation sponsored web hosting.
- [ ] Apply web page design provided below
- [ ] Fix near-indexer issue: `session is not opened` https://github.com/NEAR-labs/stats-sputnik-dao/issues/2

## 🤼‍♂️   Reviewer

@Kisgus @AngelBlock 

## 🔗   Work doc(s) / inspirational links

Current website is hosted at: https://stats.sputnik.fund

Github Repo:  https://github.com/Stardust-Staking/stats-sputnik-dao

UI Kit: https://anastasiia997987.invisionapp.com/overview/NEAR-DAO-Apps-ckp5f6sbd05jt01a6849r6gzu/screens/48316926?sortBy=1&sortOrder=1&viewLayout=2

UI to be applied: https://anastasiia997987.invisionapp.com/console/share/Q32M03K3AR/660642141
