### ISSUE TITLE
Develop request.network smart contract on NEAR

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#15]
## 🎉   Subtasks

- [x] Define functions based on #14
- [x] Add unit and integration tests
- [x] Add simulation tests
- [x] Have at least 2 experienced Rust developers review contract

## 🤼‍♂️   Reviewer

@AngelBlock
