### ISSUE TITLE
End-to-end mainnet test request.network in staging environment

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#16]
## 📋   Anything to add?

(Optional, keep it short)

## 🎉   Subtasks

- [x] Send and receive invoices on mainnet
- [x] Verify and UI glitches
- [x] Monitor tests scripts on request.network UI

## 🤼‍♂️   Reviewer

@AngelBlock
