### ISSUE TITLE
Setup call between request.network & indexer team

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#17]
## 📋   Anything to add?

Based on #16, its been concluded the indexer is giving inconsistent responses which does not satisfy the testing script requirements of request.network

## 🎉   Subtasks

- [x] Setup meeting with tech owner of indexer
- [x] Allow request.network to get recommendations on best way to go forward
- [x] Define any next action steps if needed

## 🤼‍♂️   Reviewer

@AngelBlock
