### ISSUE TITLE
Launch Twitterdrop

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#2]
## 📋   Anything to add?

Go live with Twitterdrop Monday the 6th of September.

## 🎉   Subtasks

- [ ] Generate linkdrops
- [ ] Test end to end flow
- [ ] Prepare demo video
- [ ] Connect analytics
- [ ] Launch from official account
- [ ] Evaluate results based on data, UX and public qualitative response.

## 🤼‍♂️   Reviewer

@Kisgus 

## 🔗   Work doc(s) / inspirational links

Similiar to UX of https://twitter.com/coin_artist/status/1400190624742232071?s=20

**Comment by Kisgus** [comment]
Done https://twitter.com/ParasHQ/status/1434863958587056129?s=19
