### ISSUE TITLE
Get external review feedback on Linkdrop v2 testnet contracts & propose updates if any

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#25]
## 🎉   Subtasks

- [x] Iterate with external parties
- [x] Get their feedback
- [x] Instruct needed updates if any

## 🤼‍♂️   Reviewer

@eclipseeer @Kisgus
