### ISSUE TITLE
Get Linkdrop v2 contracts into a stage of feature freeze

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#3]
## 📋   Anything to add?

Lets get the contracts ready for review and end-to-end integration with UI

## 🎉   Subtasks

- [x] Have meeting ASAP and agree on iteration of architecture
- [x] Add Campaign ID
- [x] Add Campaigns list to the User contact
- [x] Add ability to set up external linkdrop account instead of embedded 'testnet' account
- [x] Restore campaign creation/deletion if the user accidentally closed the browser 
- [x] Implement Denys preliminary review feedback 

## 🤼‍♂️   Reviewer

@AngelBlock

**Comment by eclipseeer** [comment]
Add Campaign ID - https://github.com/NEAR-labs/contracts.near-linkdrop/pull/5

**Comment by eclipseeer** [comment]
- [X] Add ability to set up external linkdrop account instead of embedded 'testnet' account - https://github.com/NEAR-labs/contracts.near-linkdrop/pull/6

**Comment by eclipseeer** [comment]
Add Campaigns list to the User contact - https://github.com/NEAR-labs/contracts.near-linkdrop/pull/8

**Comment by eclipseeer** [comment]
- [ ] Restore campaign creation/deletion if the user accidentally closed the browser - https://github.com/NEAR-labs/contracts.near-linkdrop/pull/9

**Comment by Kisgus** [comment]
Removing Denys review to #6
