### ISSUE TITLE
Prepare analytics UI for Linkdrop

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#31]
## 📋   Anything to add?

(Optional, keep it short)

## 🎉   Subtasks

- [ ] Copy the work already done from stats.sputnik.dao
- [ ] Adopt to Linkdrop specific contracts https://github.com/NEAR-labs/contracts.near-linkdrop & https://github.com/NEAR-labs/stats-sputnik-dao
- [ ] Setup testnet version of analytics side first for https://testnet.linkdrop.tech/campaigns
- [ ] Synch with @belkovair on final UI styling #19 
- [ ] Add next tasks for finalising it

## 🤼‍♂️   Reviewer

@AngelBlock
