### ISSUE TITLE
Contracts devepopment

### ISSUE THREAD

**Issue by eclipseeer** [NEAR-labs/labs-kanban#40]
## 📋   Anything to add?

Finish NFT campaign, refactor existing test and project structure

## 🎉   Subtasks

- [ ] Refactor existing tests sctucture
- [ ] Change high level architecture
- [ ] Add campaign creators
- [ ] Finish NFT campaign development
- [ ] Add tests for NFT campaign
- [ ] Refactor NEAR campaign
- [ ] Refactor NEAR campaign tests

## 🤼‍♂️   Reviewer

@eclipseeer @AngelBlock
