### ISSUE TITLE
Refactor existing tests sctucture

### ISSUE THREAD

**Issue by eclipseeer** [NEAR-labs/labs-kanban#41]
## 📋   Anything to add?

(Optional, keep it short)

## 🎉   Subtasks

- [x] Separate tests between linkdrop / user  / near_campaing folders
- [x] Refactor utils - create a separate structure for each contract (including linkdrop v1)
- [x] Refactor tests - make it more readable via reusing structures

## 🤼‍♂️   Reviewer

@eclipseeer
