### ISSUE TITLE
Finish NFT campaign development

### ISSUE THREAD

**Issue by eclipseeer** [NEAR-labs/labs-kanban#43]
## 📋   Anything to add?

At this moment we have the next methods:
- new
- claim
- nft_on_transfer
- get_drops

Need to add the next methods:
-  cancel_drop - analogue of refund_keys but for the single drop. This method will return NFT to the previous owner. May 
extend 'claim'.
- remove_drops - analogue of clear_state.
- delete_campaign - delete campaign and notify user about it

## 🎉   Subtasks

- [ ] Add cancel_drop
- [ ] Add remove_drops
- [ ] Add delete_campaign

## 🤼‍♂️   Reviewer

@eclipseeer @fedencer
