### ISSUE TITLE
Linkdrop v2 UI

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#5]
## 📋   Anything to add?

Implement UI of agreed mockups from #1 

## 🎉   Subtasks

- [x] Connect with contracts to test core functionalities
- [x] Deploy to testnet to enable to test core functionalities end-to-end as soon as possible in #6    
- [x] Finish 'Restore Access' page
- [x] Implement redirects - user should have no access to some pages while app usage. E.g if a user has a linkdrop account he shouldn't be able to reach the 'Create account' page.
- [x] Add QR code for links 
- [x] Restore campaign creation/deletion in case if these processes were interrupted
- [x] Add 'Disconnect' button
- [x] Implement 'Delete Linkdrop user' feature
- [x] Polish UX / UI and resolve identified issues in QA

## 🤼‍♂️   Reviewer

@AngelBlock
