### ISSUE TITLE
Start KYC Module project

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#60]
## 📋   Anything to add?

Getting project started by...

## 🎉   Subtasks

- [x] Creating Project - React
- [x] Setting up modules
- [x] Creating codebase structures of project

## 🤼‍♂️   Reviewer

@AngelBlock
