### ISSUE TITLE
Create new process for the Dev Labs team

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#69]
## 🎉   Subtasks

- [x] Have meeting with Denys, Karolina & Gus
- [x] Document in a google docs
- [x] Setup meetings in calendar starting from Monday the 7th of March
- [x] Start execute new process

## 🤼‍♂️   Reviewer

@Kisgus 

## 🔗   Work doc(s) / inspirational links

https://docs.google.com/document/d/1fgZO69OGBV0JlILY1nEh8LfW1ZOXuL1lj9Tjwb_W__w/edit
