### ISSUE TITLE
Deploy Linkdrop v2 contracts to mainnet & test end-to-end

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#7]
## 📋   Anything to add?

Once #3, #4 is done and we have had external people to look at the contract, its time to go to mainnet

## 🎉   Subtasks

- [x] Deploy to mainnet
- [x] Switch UI to mainnet
- [x] Test internally and have external review before public launch

## 🤼‍♂️   Reviewer

@AngelBlock
