### ISSUE TITLE
Kickoff NFT and Fungible token call 

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#8]
## 📋   Anything to add?

(Optional, keep it short)

## 🎉   Subtasks

- [x] Summon leading NFT and Fungible token projects to get their input on our proposed Linkdrop implementation
- [x] Post proposal on gov.forum
- [x] Finish specification and split into issues for implementation

## 🤼‍♂️   Reviewer

@AngelBlock

**Comment by Kisgus** [comment]
We've gathered feedback from Abridged, Mintbase & Paras and asked Satori for input. Currently we are blocked to finish the final specification by the ongoing "NFT standarization work group". We're staying closely up to date with this.
