### ISSUE TITLE
Include Ref Staking Rewards

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#91]
## 📋   Anything to add?

The NEAR ecosystem needs to easier track their farming activities from Ref.finance:

## 🎉   Subtasks

- [ ] Track LP tokens
- [ ] Track Farming rewards
- [ ] Track xRef staking
- [ ] Track stableswap / "Sauce

## 🤼‍♂️   Reviewer

@AngelBlock
